### ISSUE TITLE
Idea: deleting fontifies latex macros in one go.

### ISSUE THREAD

**Issue by guraltsev** [zk-phi/magic-latex-buffer#13]
After using magic-latex-buffer mode for some time I noticed that once some macro gets fontified (like greek letters, math symbols escaped brackets, etc..) it would be much more efficient to erase the whole macro when backspacing or deleting rather than only the last (or first) letter and so on. Effectively once the macro has been typed for me it becomes one entity.

I could try to implement such a behavior however I am not very experienced. Are there tools for such behavior in the overlay functionality of emacs? Any tips would be great. Thanks!

**Comment by zk-phi** [comment]
Current behavior is fine for me, but it can also be an option.

I think the easiest implementation is to add a function that deletes whole overlayed text, to the overlay's `modification-hooks`.

**Comment by guraltsev** [comment]
Ok, I'll try to look into this and make this behavior dependent on some variable.

**Comment by zk-phi** [comment]
closing.
