### ISSUE TITLE
Add symbol for `\implies`

### ISSUE THREAD

**Issue by cute-jumper** [zk-phi/magic-latex-buffer#14]
Thank you for the awesome extension. I use `\implies` often, which looks like `\Longrightarrow`. They only differ a little. Since both short and long rightwards arrows have been used, I think maybe a variant of rightwards arrow can be used. I locally add ⇨ as the symbol for `\implies` to the set of `ml/relation-symbols`, but it's not perfect. Do you have any idea about adding the symbol for `implies`? Thanks.

**Comment by zk-phi** [comment]
Thank you for your contribution.

`magic-latex-buffer` already maps some commands to the same unicode symbol, so I think using the same symbol as `\Longrightarrow` is okay. It'll be harder to distinguish `\Longrightarrow` and `\implies` that case, but I think it's not really a problem. How do you think?

**Comment by cute-jumper** [comment]
I think that would be nice. I've created a pull request #15 , which adds the same symbol for `\implies` as `\Longrightarrow`.
