### ISSUE TITLE
Odd substitutions

### ISSUE THREAD

**Issue by paxperscientiam** [zk-phi/magic-latex-buffer#17]
Hi! Wow, what a great emacs-package! I just started testing and while I'm very impressed I have noticed some odd substitutions.

For instance, "\begin" and "\end" are both substituted with the del symbol. Why might this be? Something to do with AUCTeX perhaps?

**Comment by zk-phi** [comment]
Just because I felt "\begin" "\end" are too much.

All we want to know from the commands is where the current environment starts and ends, and the char sequence "\begin", "\end" is not really important. Thus I thought some abbreviations maybe helpful for reading.

If the behavior is not suitable, you can modify `ml/other-symbols' to remove some (non-mathematical) substitutions anyway.

**Comment by paxperscientiam** [comment]
Hi @zk-phi 

Now I'm on the same page as you. What about something a bit less ambiguous?

For instance,
```
"\begin" => "α"
"\end" => "ω"
```
At the very least, I don't the the same symbol should be used to indicate both the opening and closing of some environment.
This would correspond to the first and last letters of the Greek alphabet. Seems fitting to me. Thoughts?

Thanks for informing me about customization; I appreciate that.

**Comment by zk-phi** [comment]
> This would correspond to the first and last letters of the Greek alphabet. Seems fitting to me.
> Thoughts?

It's exactly true that "\begin" and "\end" should be easy to distinguish, but IMO, in addition, "\begin" and "\end" should be also VISUALLY paired for the ease of reading.

Since "△" and "▽" are visually (and vertically) paired, they're suitable to represent where the environment begins and ends I thought.

````
▽{foo}
  blah, blah, blah, ...
△{foo}
````

"α" and "ω" are not visually paired (while they are semantically paired), so IMO they're not as intuitive as "△" "▽".

````
α{foo}
  blah, blah, blah, ...
ω{foo}
````

How do you think?

**Comment by paxperscientiam** [comment]
I think your points are valid; but, I think semantic approach becomes preferable for environments that stretch on for, say, multiple buffer lengths. I think it's easier to remember that omega is last and alpha is first (then again, that is predicated on the end-user being familiar with Greek alphabet). Delta and upside-down delta are certainly more visually appealing -- when in close proximity.

Perhaps you could allow end-user to easily choose between "semantic" pair and "visual" pair? If not, then perhaps use more pointed triangles instead of deltas as mixed usage of deltas could be confusing to some (maybe only noobies).

**Comment by zk-phi** [comment]
> Perhaps you could allow end-user to easily choose between "semantic" pair and "visual" pair?

Accepting dynamic configuration change may lead to a performance issue, so symbols should be better defined statically (in the source code).

> use more pointed triangles instead of deltas as mixed usage of deltas could be confusing to some

I've tried some other alternatives but found nothing suitable... Any ideas?

**Comment by paxperscientiam** [comment]
I know it's been a while -- sorry! -- but I just got an idea for a feature that would go nicely with magic-latex-buffer. Basically, when the cursor is on a magic symbol, display the actual text in the minibuffer. This would keep things pretty whilst allowing for a sanity check via the minibuffer.

More to the original point, I dug around a bit and it seems that delta is the best character for the job (visually speaking). I would fiddle around to suit my original taste, but your method has grown on me.

**Comment by zk-phi** [comment]
Hi, 

> Basically, when the cursor is on a magic symbol, display the actual text in the minibuffer. This would keep things pretty whilst allowing for a sanity check via the minibuffer.

This seems a good idea!

Currently `magic-latex-buffer' maps some different commands to the same symbol and it's hard to distinguish them, but the approach solves the problem too.

I'll implement the feature when I have some time off, thanks.

**Comment by paxperscientiam** [comment]
You're welcome :)

**Comment by zk-phi** [comment]
implemented.

**Comment by paxperscientiam** [comment]
@zk-phi Nice work; it works great!
