### ISSUE TITLE
Better context detection (underscores and possibly other stuff)

### ISSUE THREAD

**Issue by paxperscientiam** [zk-phi/magic-latex-buffer#19]
Hi @zk-phi 

I've been keeping my install in sync with your releases, so I don't believe this is related to being on an old version.

I understand that underscore is a special character; however, there are certain contexts where hiding it is undesirable. For instance, when using a class name with an underscore. This `\ProvidesClass{my_invoice}` is rendered as `\ProvidesClass{myinvoice}`. I think in this context that characters should not be obfuscated.

This is the only character ('_') that needs context adjustments that I know of.

Can this be remedied?

**Comment by zk-phi** [comment]
thanks.

it seems that we should add some keywords to `ml/keywords-1`, which defines a list of special commands that takes filename, classname, ... etc as their argument.

can you provide me a list of popular commands that cause the same problem (sorry but I'm quite novice in LaTeX)?

**Comment by paxperscientiam** [comment]
I wonder if the inverse problem might be easier to solve. What about RegEx matching? Before an underscore is hidden, it could be determined whether or not there is a preceding "$" on the same line. I suppose the proper RegEx would check for the presence of a "\" immediately preceding the "$". This would ensure that underscore is only hidden with inline math-mode.

What do you think of that as a starting point?

**Comment by zk-phi** [comment]
how about this?

````
$foo$ bar_baz
````

the `_' has a preceding `$' on the same line

**Comment by paxperscientiam** [comment]
Let me think further about this, because it is more complicated. The regular expression implementation would also need to look "ahead" and "behind"...I think.

The expression `/(?<!\\)\$[^\$].+\_.+[^\\$]\$/` might work, but it might also be slow to match. Though not always accurate, it might be better, at least initially, to simply test if there are two literal "$" on a given line.

I'm unfortunately not an expert (far from it) in RegEx, nor in lisp.

Another problem is that I don't think Emacs natively support "look ahead" and "look behind," which might mean you'll need another dependency. Not ideal.

**Comment by zk-phi** [comment]
Closing. Please reopen if you have any other ideas or insights.
