### ISSUE TITLE
how to customize symbols?

### ISSUE THREAD

**Issue by scaramouche1** [zk-phi/magic-latex-buffer#23]
Many thanks for this great new package!

I have one question: say I do not like some of the symbol replacements (e.g., a right hand to represent \ref).  How can I disable or modify that replacement?  Similarly, can I disable a whole set of symbols? (e.g., `ml/other-symbols`).

**Comment by zk-phi** [comment]
there's no way to customize dynamically, and you need to modify the source code.
to remove all symbols in `ml/other-symbols`, replace the definition of `ml/other-symbols` with `'()`.

````
(defconst ml/other-symbols
  '())
````
