### ISSUE TITLE
Double subscripts are confusing.

### ISSUE THREAD

**Issue by guraltsev** [zk-phi/magic-latex-buffer#6]
Example:

write a subsequence:

$a_{n_k}$

Since the $_$ character does not get displayed in math mode it is impossible to understand that we have written down a subsequence. The font does not get smaller so there is no way whatsoever to understand what is happening. This impedes the usability of the package drastically, and that is unfortunate since I find it very nice and useful. A temporary fix could be to reenable displaying the underscore.

**Comment by zk-phi** [comment]
Thanks for reporting.
I just implemented better fontifier for nested super/sub-scripts. Please try the latest version :)
