### ISSUE TITLE
Highlighting inconsistent

### ISSUE THREAD

**Issue by guraltsev** [zk-phi/magic-latex-buffer#7]
When using magic-latex-buffer with AucTeX in emacs 24.4.1 there is inconsistent application of coloring to math formulas. Formulas in display math environments get highlighted correctly so that LaTeX macros appear in a different color. However formulas in inline math mode (enclosed in single $) are the normal AucTeX face and do not get affected.

**Comment by zk-phi** [comment]
`magic-latex-buffer` is designed to be used with `latex-mode` so AucTeX is not supported for now.
(contributions are welcome!)

**Comment by guraltsev** [comment]
I had an opportunity to test `magic-latex-buffer` in `latex-mode` (I ran a clean emacs with no packages installed) and manually loaded `magic-latex-buffer`.  The highlighting is still inconsistent even in `latex-mode`. Here is a screenshot:
![snapshot-inconsistent-highlighting](https://cloud.githubusercontent.com/assets/7040974/9324630/dd46ead0-4594-11e5-8cc9-643854b0aba0.png)

**Comment by zk-phi** [comment]
ah, I see, you mean something like this ?

````
(defun tex-font-lock-syntactic-face-function (s)
  nil)
````

this will make latex-mode not to highlight inline math environments.

**Comment by zk-phi** [comment]
closing (maybe solved or not interested anymore ?)
