### ISSUE TITLE
All whitespaces in math mode are the same

### ISSUE THREAD

**Issue by guraltsev** [zk-phi/magic-latex-buffer#8]
All spacing symbols in math displays appear as the same glyph. This is slightly confusing (and sometimes unpractical) when \, \; \quad \qquad all get displayed the same. Although if I understand correctly these are just Unicode glyphs so I doubt that there are different length glyphs.... What could be a solution?

**Comment by zk-phi** [comment]
I couldn't find suitable Unicode chars.
Do you have any ideas about how they should be displayed?

**Comment by zk-phi** [comment]
not interested anymore ...?
